# Le nom du workflow (il apparaîtra dans l'onglet Actions sur GitHub).
name: Hello World Workflow

# Les déclencheurs : le workflow s'exécutera lors d'un push ou d'une pull request sur la branche main.
on:
  push:               # Déclencheur pour un push
    branches:
      - main          # Sur la branche main uniquement
  pull_request:       # Déclencheur pour une pull request
    branches:
      - main          # Sur la branche main uniquement

jobs:
  # Contient les tâches à exécuter. Ici, le job s'appelle "greeting".
  greeting:
    # Indique que le workflow s'exécutera sur une machine Ubuntu.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # Étape 1 : Afficher "Hello World" dans les logs.
      - name: Print Hello World
        run: echo "Hello World"  # Commande pour afficher un message simple dans les logs.

      # Étape 2 : Configurer Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18     # Définit la version de Node.js à utiliser.

      # Étape 3 : Installer les dépendances.
      - name: Install dependencies
        run: npm install          # Installe les dépendances définies dans package.json.

      # Étape 4 : Exécuter le linter.
      - name: Run lint
        run: npm run lint          # Vérifie la qualité du code avec le script lint.


